name : Genrate Prodcast Feeds
on : [push]
jobs:
  builds:
    runs-on : ubuntu-latest
    steps:
      - name : Checkout Repo
        uses: actions/checkout@v3
      - name : Run Feed Generator
        uses : yashpatle23/github-podcast-genorator@main
